import type { Metadata } from "next"
import { ThemeProvider } from "@/components/ThemeProvider"
import { ClerkProvider } from "@clerk/nextjs"
import Header from "@/components/Header"

export const metadata: Metadata = {
  title: "Learning Management System",
  description: "Generated by create next app",
}

export default function UserLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="flex-1">
            {children}
          </main>
        </div>
      </ThemeProvider>
    </ClerkProvider>
  )
}
